Opt out interfaces
hmil/tslint-override pull request #10
Opened 2018-07-28 11:04 UTC by stasberkov

Implementation for Issue #5

2018-07-28 11:27 UTC, hmil requested changes
Thank you, looks good. There are a few issues with formatting (I am using two tabs for arguments lists, even though you caught some inconsistencies too).

Regarding testing, until now the behavior with respect to interfaces was left unspecified. You should add an interface in "spec.ts.lint" and make sure that tslint reports an error when the override keyword is missing and when it is extraneous.
Then, the test you added will be sufficient to ensure that interfaces are excluded when the `exclude-interfaces` flag is provided.

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +    ts.JSDocTag;
Please keep the indentation unchanged.

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +        private readonly checker: ts.TypeChecker) {
Same here. To indents is for arguments lists, one indent for code blocks.

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +                break;
This was actually a mistake, good catch 😉

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +                Lint.Replacement.deleteText(foundKeyword.getStart(), foundKeyword.getWidth()));
Keep the tab

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +                Lint.Replacement.deleteText(foundKeyword.getStart(), foundKeyword.getWidth()));
Keep the tab

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +                    Lint.Replacement.deleteText(foundKeyword.getStart(), foundKeyword.getWidth()));
Keep the tab

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +                Lint.Replacement.deleteText(foundKeyword.getStart(), foundKeyword.getWidth()));
Add a second tab

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +                Lint.Replacement.deleteFromTo(dec.pos, dec.end));
Keep the tab

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +                Lint.Replacement.deleteFromTo(child.pos, child.end));
Keep the tab

2018-07-28 11:27 UTC, hmil commented on rules/explicitOverrideRule.ts
> +        : ts.Type | undefined {
Keep the tab

2018-07-28 15:58 UTC, stasberkov commented
What editor do yo use? Do you use auto code reformat feature of code editor?  In VS Code this it triggered by Alt+Shift+F. These indent-releated changes were done by VS Code autoformat. I will rollback them if you want.

2018-07-28 19:46 UTC, stasberkov commented
Please review

2018-07-29 14:40 UTC, hmil approved these changes

2018-07-29 14:40 UTC, merged